In this assignement, feel free to use the `sparse` module from `scipy`.

Use the cell below for your imports.

In [1]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, coo_matrix

implement the function `mat_mul_coo` that takes two sparse matrices in `coo` and returns their product.

In [35]:
from scipy.sparse import coo_matrix

def mat_mul_coo(A, B):
    # Make sure the matrices are in COO format
    A = A.tocoo()
    B = B.tocoo()
    
    # Check if the dimensions are compatible for matrix multiplication
    if A.shape[1] != B.shape[0]:
        raise ValueError("Matrices are not compatible for multiplication")
        
    # Convert matrices to dictionaries
    A_dict = {(A.row[i], A.col[i]): A.data[i] for i in range(len(A.data))}
    B_dict = {(B.row[i], B.col[i]): B.data[i] for i in range(len(B.data))}
    
    # Compute the product of the two matrices
    AB_dict = {}
    for key1, val1 in A_dict.items():
        for key2, val2 in B_dict.items():
            # Check if the columns of matrix A match the rows of matrix B
            if key1[1] == key2[0]:
                # Compute the dot product and store the result in a dictionary
                if (key1[0], key2[1]) in AB_dict:
                    AB_dict[(key1[0], key2[1])] += val1 * val2
                else:
                    AB_dict[(key1[0], key2[1])] = val1 * val2
    
    # Convert the resulting dictionary to COO format
    row = []
    col = []
    data = []
    for key, val in AB_dict.items():
        row.append(key[0])
        col.append(key[1])
        data.append(val)
    
    # Create a new COO matrix from the resulting data
    return coo_matrix((data, (row, col))).toarray()


In [56]:
a = [[7,8,0],[7,0,5],[4,0,6]]
b = [[3,0,1],[0,6,0],[5,0,2]]
A = coo_matrix(a)
B = coo_matrix(b)
print(mat_mul_coo(A, B))

[[21 48  7]
 [46  0 17]
 [42  0 16]]


implement the function `mat_mul_csr` that takes two sparse matrices in `csr` format and returns their product.

In [44]:
def mat_mul_csr(A, B):
    # Make sure the matrices are in CSR format
    A = A.tocsr()
    B = B.tocsr()

    # Check if the dimensions are compatible for matrix multiplication
    if A.shape[1] != B.shape[0]:
        raise ValueError("Matrices are not compatible for multiplication")
    
    # Create an empty CSR matrix to hold the result
    C = csr_matrix((A.shape[0], B.shape[1]), dtype=np.float64)
    
    # Perform the matrix multiplication using CSR format
    C = A.dot(B)
    
    return C.toarray()

In [55]:
a = csr_matrix([[1,0,0],[2,0,0],[2,0,0]])
b = csr_matrix([[4,5,0],[7,0,8],[0,4,4]])
print(mat_mul_csr(a, b))

[[ 4  5  0]
 [ 8 10  0]
 [ 8 10  0]]


implement a function `solve_lin_sys` that takes a matrix `A` in `csr` format and a vector `b` as a numpy array and solves the system `Ax = b`.

In [46]:
from scipy.sparse.linalg import spsolve

def solve_lin_sys(A, b):
    # Make sure the matrix is in CSR format
    A = A.tocsr()

    # Solve the linear system using the spsolve function from scipy.sparse.linalg
    x = spsolve(A, b)
    
    return x

In [54]:
A = csr_matrix([[1, 0, 3], [0, 5, 6], [7, 0, 9]])
b = np.array([8, 6, 4])
print(solve_lin_sys(A, b))
print(np.linalg.solve(A.toarray(), b))

[-5.         -4.          4.33333333]
[-5.         -4.          4.33333333]
